name: Release PromptHelper

on:
  push:
    branches:
      - main # 或你希望触发此工作流的分支

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: 设置 Node.js 环境
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      
      - name: 生成新的 prompthelper.js
        run: node scripts/generate-prompthelper.js

      - name: 基于时间戳推送新的tag
        run: |
          TIMESTAMP=`date +%Y%m%d%H%M%S`
          echo "NEW_TAG_NAME=v$TIMESTAMP" >> $GITHUB_ENV
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag $NEW_TAG_NAME $(git rev-parse HEAD)
          git push origin $NEW_TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - name: 发布
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      
      - name: 上传文件
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/generated/prompthelper.js
          asset_name: prompthelper.js
          asset_content_type: application/javascript
